"""Add timezone awareness to_be_observed_at* pfs_design/pfs_config

Revision ID: 06febe7976d8
Revises: 5170e0ba92c5
Create Date: 2025-11-19 23:23:33.575544

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06febe7976d8'
down_revision = '5170e0ba92c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pfs_config', 'to_be_observed_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_comment='Planned observation time creating the pfsConfig',
                    existing_nullable=True,
                    postgresql_using="to_be_observed_at AT TIME ZONE 'UTC'")
    op.alter_column('pfs_config', 'to_be_observed_at_design',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_comment='Planned observation time creating the pfsDesign',
                    existing_nullable=True,
                    postgresql_using="to_be_observed_at_design AT TIME ZONE 'UTC'")
    op.alter_column('pfs_design', 'to_be_observed_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_comment='Planned observation time creating the pfsDesign',
                    existing_nullable=True,
                    postgresql_using="to_be_observed_at AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('pfs_design', 'to_be_observed_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_comment='Planned observation time creating the pfsDesign',
                    existing_nullable=True,
                    postgresql_using="to_be_observed_at AT TIME ZONE 'UTC'")

    op.alter_column('pfs_config', 'to_be_observed_at_design',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_comment='Planned observation time creating the pfsDesign',
                    existing_nullable=True,
                    postgresql_using="to_be_observed_at_design AT TIME ZONE 'UTC'")

    op.alter_column('pfs_config', 'to_be_observed_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_comment='Planned observation time creating the pfsConfig',
                    existing_nullable=True,
                    postgresql_using="to_be_observed_at AT TIME ZONE 'UTC'")

    # ### end Alembic commands ###
