"""updating models for pfs_design, pfs_config, pfs_config_sps

Revision ID: 17dc946014c1
Revises: aa5ab36a351a
Create Date: 2025-03-18 16:40:34.178334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17dc946014c1'
down_revision = 'aa5ab36a351a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pfs_config', sa.Column('to_be_observed_at', sa.DateTime(), nullable=True, comment='Planned observation time creating the pfsConfig'))
    op.add_column('pfs_config', sa.Column('pfs_utils_version', sa.String(), nullable=True, comment='pfs_utils version creating the pfsConfig'))
    op.add_column('pfs_config', sa.Column('to_be_observed_at_design', sa.DateTime(), nullable=True, comment='Planned observation time creating the pfsDesign'))
    op.add_column('pfs_config', sa.Column('pfs_utils_version_design', sa.String(), nullable=True, comment='pfs_utils version creating the pfsDesign'))
    op.add_column('pfs_config_sps', sa.Column('cam_mask', sa.Integer(), nullable=True, comment='bitMask describing which cameras were use for this visit.'))
    op.add_column('pfs_config_sps', sa.Column('inst_status_flag', sa.Integer(), nullable=True, comment='Bitmask indicating instrument-related status flags for this visit.'))
    op.add_column('pfs_design', sa.Column('pfs_utils_version', sa.String(), nullable=True, comment='pfs_utils version creating the pfsDesign'))
    op.alter_column('pfs_design', 'to_be_observed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Planned observation time creating the pfsDesign',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pfs_design', 'to_be_observed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Planned observation time creating the pfsDesign',
               existing_nullable=True)
    op.drop_column('pfs_design', 'pfs_utils_version')
    op.drop_column('pfs_config_sps', 'inst_status_flag')
    op.drop_column('pfs_config_sps', 'cam_mask')
    op.drop_column('pfs_config', 'pfs_utils_version_design')
    op.drop_column('pfs_config', 'to_be_observed_at_design')
    op.drop_column('pfs_config', 'pfs_utils_version')
    op.drop_column('pfs_config', 'to_be_observed_at')
    # ### end Alembic commands ###
