"""fix for INSTRM-2041

Revision ID: 1a6070b36cbb
Revises: cc9a305bad2c
Create Date: 2023-07-25 18:50:42.961664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6070b36cbb'
down_revision = 'cc9a305bad2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agc_guide_offset', sa.Column('guide_delta_scale', sa.REAL(), nullable=True, comment='The calculated scale offset [arcsec.]'))
    op.add_column('agc_guide_offset', sa.Column('mask', sa.Integer(), nullable=True, comment='A mask of the active elements being fit'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agc_guide_offset', 'mask')
    op.drop_column('agc_guide_offset', 'guide_delta_scale')
    # ### end Alembic commands ###
