"""update to 0.0.4

Revision ID: 308ade0f3929
Revises: 539e0541a4d3
Create Date: 2020-12-22 20:48:52.928380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308ade0f3929'
down_revision = '539e0541a4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obslog_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('obslog_visit_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pfs_visit_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pfs_visit_id'], ['pfs_visit.pfs_visit_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['obslog_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obslog_visit_set_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visit_set_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['obslog_user.id'], ),
    sa.ForeignKeyConstraint(['visit_set_id'], ['sps_sequence.visit_set_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obslog_mcs_exposure_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mcs_exposure_frame_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mcs_exposure_frame_id'], ['mcs_exposure.mcs_frame_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['obslog_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obslog_mcs_exposure_note')
    op.drop_table('obslog_visit_set_note')
    op.drop_table('obslog_visit_note')
    op.drop_table('obslog_user')
    # ### end Alembic commands ###
