"""fix for INSTRM-1955

Revision ID: 3822060eb2ca
Revises: 1a6070b36cbb
Create Date: 2023-07-25 22:54:13.696791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3822060eb2ca'
down_revision = '1a6070b36cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tel_status', sa.Column('inst_pa', sa.REAL(), nullable=True, comment='The INST_PA at which the exposure started [deg]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tel_status', 'inst_pa')
    # ### end Alembic commands ###
