"""DAMD-173

Revision ID: 3c79be472316
Revises: 17dc946014c1
Create Date: 2025-03-18 15:51:03.416977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c79be472316'
down_revision = '17dc946014c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pfs_design_agc', sa.Column('guide_star_flag', sa.Integer(), nullable=True, comment='GuideStar catalog flag'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfs_design_agc', 'guide_star_flag')
    # ### end Alembic commands ###
