"""add pfs_config_fiber.pfi_nominal_final..

Revision ID: 40988b7668ba
Revises: 319ff2529bc2
Create Date: 2023-02-07 14:25:05.737251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40988b7668ba'
down_revision = '319ff2529bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment='',
    #            existing_nullable=True)
    op.add_column('pfs_config_fiber', sa.Column('pfi_nominal_final_x_mm', sa.REAL(), nullable=True))
    op.add_column('pfs_config_fiber', sa.Column('pfi_nominal_final_y_mm', sa.REAL(), nullable=True))
    op.create_unique_constraint(None, 'pfs_config_sps', ['pfs_visit_id', 'visit0'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pfs_config_sps', type_='unique')
    op.drop_column('pfs_config_fiber', 'pfi_nominal_final_y_mm')
    op.drop_column('pfs_config_fiber', 'pfi_nominal_final_x_mm')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment=None,
    #            existing_comment='',
    #            existing_nullable=True)
    # op.create_table('test',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
    # )
    # ### end Alembic commands ###
