"""update to 0.1.9

Revision ID: 431d0bb8a39d
Revises: efacacfa24d5
Create Date: 2021-11-17 17:37:08.631593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431d0bb8a39d'
down_revision = 'efacacfa24d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agc_guide_offset',
                    sa.Column('agc_exposure_id', sa.Integer(), autoincrement=False, nullable=False, comment='AGC exposure number identifier'),
                    sa.Column('guide_ra', sa.FLOAT(), nullable=True, comment='The designed FoV R.A. center [deg.]'),
                    sa.Column('guide_dec', sa.FLOAT(), nullable=True, comment='The designed FoV Dec. center [deg.]'),
                    sa.Column('guide_pa', sa.REAL(), nullable=True, comment='The designed FoV PA [deg.]'),
                    sa.Column('guide_delta_ra', sa.REAL(), nullable=True, comment='The calculated FoV R.A. offset [arcsec.]'),
                    sa.Column('guide_delta_dec', sa.REAL(), nullable=True, comment='The calculated FoV Dec. offset [arcsec.]'),
                    sa.Column('guide_delta_insrot', sa.REAL(), nullable=True, comment='The calculated InsRot offset [arcsec.]'),
                    sa.Column('guide_delta_az', sa.REAL(), nullable=True, comment='The calculated Az offset [arcsec.] (optional)'),
                    sa.Column('guide_delta_el', sa.REAL(), nullable=True, comment='The calculated El offset [arcsec.] (optional)'),
                    sa.Column('guide_delta_z', sa.REAL(), nullable=True, comment='The calculated focus offset [mm]'),
                    sa.Column('guide_delta_z1', sa.REAL(), nullable=True, comment='The calculated focus offset for AGC1 [mm]'),
                    sa.Column('guide_delta_z2', sa.REAL(), nullable=True, comment='The calculated focus offset for AGC2 [mm]'),
                    sa.Column('guide_delta_z3', sa.REAL(), nullable=True, comment='The calculated focus offset for AGC3 [mm]'),
                    sa.Column('guide_delta_z4', sa.REAL(), nullable=True, comment='The calculated focus offset for AGC4 [mm]'),
                    sa.Column('guide_delta_z5', sa.REAL(), nullable=True, comment='The calculated focus offset for AGC5 [mm]'),
                    sa.Column('guide_delta_z6', sa.REAL(), nullable=True, comment='The calculated focus offset for AGC6 [mm]'),
                    sa.ForeignKeyConstraint(['agc_exposure_id'], ['agc_exposure.agc_exposure_id'], ),
                    sa.PrimaryKeyConstraint('agc_exposure_id')
                    )
    op.alter_column('agc_data', 'image_moment_00_pix',
                    existing_type=sa.REAL(),
                    comment='',
                    existing_nullable=True)
    op.add_column('agc_exposure', sa.Column('measurement_algorithm', sa.String(), nullable=True, comment='Spot measurement algorithm (windowed/sep)'))
    op.add_column('agc_exposure', sa.Column('version_actor', sa.String(), nullable=True, comment='Version of the actor'))
    op.add_column('agc_exposure', sa.Column('version_instdata', sa.String(), nullable=True, comment='Version of the pfs_instdata'))
    op.add_column('mcs_exposure', sa.Column('measurement_algorithm', sa.String(), nullable=True, comment='Spot measurement algorithm (windowed/sep)'))
    op.add_column('mcs_exposure', sa.Column('version_actor', sa.String(), nullable=True, comment='Version of the actor'))
    op.add_column('mcs_exposure', sa.Column('version_instdata', sa.String(), nullable=True, comment='Version of the pfs_instdata'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcs_exposure', 'version_instdata')
    op.drop_column('mcs_exposure', 'version_actor')
    op.drop_column('mcs_exposure', 'measurement_algorithm')
    op.drop_column('agc_exposure', 'version_instdata')
    op.drop_column('agc_exposure', 'version_actor')
    op.drop_column('agc_exposure', 'measurement_algorithm')
    op.alter_column('agc_data', 'image_moment_00_pix',
                    existing_type=sa.REAL(),
                    comment=None,
                    existing_comment='',
                    existing_nullable=True)
    op.create_table('test',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
                    )
    op.drop_table('agc_guide_offset')
    # ### end Alembic commands ###
