"""update to 0.1.11

Revision ID: 4b795e4f3a76
Revises: 3078fbf3ffdb
Create Date: 2021-11-20 16:19:03.548596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b795e4f3a76'
down_revision = '3078fbf3ffdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiducial_fiber_match',
                    sa.Column('pfs_visit_id', sa.Integer(), autoincrement=False, nullable=False, comment='PFS visit identifier'),
                    sa.Column('iteration', sa.Integer(), autoincrement=False, nullable=False, comment='Iteration number for this frame'),
                    sa.Column('fiducial_fiber_id', sa.Integer(), autoincrement=False, nullable=False, comment='Fiducial fiber identifier'),
                    sa.Column('mcs_frame_id', sa.Integer(), autoincrement=False, nullable=True, comment='MCS frame identifier as generated from Gen2'),
                    sa.Column('spot_id', sa.Integer(), autoincrement=False, nullable=True, comment='Corresponding MCS image spot identifier '),
                    sa.Column('flags', sa.Integer(), nullable=True, comment='flags for movement etc.'),
                    sa.ForeignKeyConstraint(['mcs_frame_id', 'spot_id'], ['mcs_data.mcs_frame_id', 'mcs_data.spot_id'], ),
                    sa.PrimaryKeyConstraint('pfs_visit_id', 'iteration', 'fiducial_fiber_id'),
                    sa.UniqueConstraint('pfs_visit_id', 'iteration', 'fiducial_fiber_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fiducial_fiber_match')
    # ### end Alembic commands ###
