"""infra-351 pfs_config_agc add guide_star_ra guide_star_dec columns

Revision ID: 5170e0ba92c5
Revises: 306be143cb55
Create Date: 2025-09-05 16:09:58.732687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5170e0ba92c5'
down_revision = '306be143cb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment='',
    #            existing_nullable=True)
    op.add_column('pfs_config_agc', sa.Column('guide_star_ra', sa.FLOAT(), nullable=True, comment='GuideStar R.A. [deg.]'))
    op.add_column('pfs_config_agc', sa.Column('guide_star_dec', sa.FLOAT(), nullable=True, comment='GuideStar Dec. [deg.]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfs_config_agc', 'guide_star_dec')
    op.drop_column('pfs_config_agc', 'guide_star_ra')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment=None,
    #            existing_comment='',
    #            existing_nullable=True)
    # op.create_table('test',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
    # )
    # ### end Alembic commands ###
