"""update to 0.0.3

Revision ID: 539e0541a4d3
Revises: 30384f37a7f3
Create Date: 2020-11-16 10:10:13.110683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539e0541a4d3'
down_revision = '30384f37a7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pfs_visit', sa.Column('issued_at', sa.DateTime(), nullable=True, comment='Issued time [YYYY-MM-DDThh:mm:ss]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfs_visit', 'issued_at')
    # ### end Alembic commands ###
