"""test 2

Revision ID: 583bc21c4e6f
Revises: d09bde8d956b
Create Date: 2020-10-12 12:06:31.981619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583bc21c4e6f'
down_revision = 'd09bde8d956b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sps_exposure', 'exptime', new_column_name='exptime2')
    op.add_column('sps_exposure', sa.Column('test', sa.Integer(), nullable=True, comment='beam switch mode id'))
    op.create_foreign_key(None, 'sps_exposure', 'beam_switch_mode', ['test'], ['beam_switch_mode_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sps_exposure', 'exptime2', new_column_name='exptime')
    op.drop_constraint(None, 'sps_exposure', type_='foreignkey')
    op.drop_column('sps_exposure', 'test')
    # ### end Alembic commands ###
