"""add inst_pa

Revision ID: 5dadaac87b5b
Revises: ecf87508e91f
Create Date: 2023-04-27 01:33:58.922258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dadaac87b5b'
down_revision = 'ecf87508e91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agc_exposure', sa.Column('inst_pa', sa.REAL(), nullable=True, comment='The INST_PA at which the exposure started [deg]'))
    op.add_column('tel_status', sa.Column('inst_pa', sa.REAL(), nullable=True, comment='The INST_PA at which the exposure started [deg]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tel_status', 'inst_pa')
    op.drop_column('agc_exposure', 'inst_pa')
    # ### end Alembic commands ###
