"""rename pfs_config.pfi_nominal_final..

Revision ID: 68dcfec061dc
Revises: 40988b7668ba
Create Date: 2023-03-03 18:35:44.553424

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '68dcfec061dc'
down_revision = '40988b7668ba'
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.alter_column('pfs_config_fiber', 'pfi_nominal_final_x_mm', new_column_name='pfi_nominal_x_mm')
    op.alter_column('pfs_config_fiber', 'pfi_nominal_final_y_mm', new_column_name='pfi_nominal_y_mm')

    op.alter_column('pfs_config_fiber', 'pfi_nominal_x_mm',
                    existing_type=sa.REAL(),
                    comment='Nominal x-position on the PFI')
    op.alter_column('pfs_config_fiber', 'pfi_nominal_y_mm',
                    existing_type=sa.REAL(),
                    comment='Nominal y-position on the PFI')
    op.alter_column('pfs_config_fiber', 'pfi_center_final_x_mm',
                    existing_type=sa.REAL(),
                    comment='Final measured x-position on the PFI')
    op.alter_column('pfs_config_fiber', 'pfi_center_final_y_mm',
                    existing_type=sa.REAL(),
                    comment='Final measured y-position on the PFI')

    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #                 existing_type=sa.REAL(),
    #                 comment='',
    #                 existing_nullable=True)
    # op.add_column('pfs_config_fiber',
    #               sa.Column('pfi_nominal_x_mm', sa.REAL(), nullable=True, comment='Nominal x-position on the PFI'))
    # op.add_column('pfs_config_fiber',
    #               sa.Column('pfi_nominal_y_mm', sa.REAL(), nullable=True, comment='Nominal y-position on the PFI'))
    # op.alter_column('pfs_config_fiber', 'pfi_center_final_x_mm',
    #                 existing_type=sa.REAL(),
    #                 comment='Final measured x-position on the PFI',
    #                 existing_nullable=True)
    # op.alter_column('pfs_config_fiber', 'pfi_center_final_y_mm',
    #                 existing_type=sa.REAL(),
    #                 comment='Final measured y-position on the PFI',
    #                 existing_nullable=True)
    # op.drop_column('pfs_config_fiber', 'pfi_nominal_final_x_mm')
    # op.drop_column('pfs_config_fiber', 'pfi_nominal_final_y_mm')
    # ### end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.alter_column('pfs_config_fiber', 'pfi_nominal_x_mm', new_column_name='pfi_nominal_final_x_mm')
    op.alter_column('pfs_config_fiber', 'pfi_nominal_y_mm', new_column_name='pfi_nominal_final_y_mm')

    op.alter_column('pfs_config_fiber', 'pfi_nominal_final_x_mm',
                    existing_type=sa.REAL(),
                    comment=None)
    op.alter_column('pfs_config_fiber', 'pfi_nominal_final_y_mm',
                    existing_type=sa.REAL(),
                    comment=None)
    op.alter_column('pfs_config_fiber', 'pfi_center_final_x_mm',
                    existing_type=sa.REAL(),
                    comment=None)
    op.alter_column('pfs_config_fiber', 'pfi_center_final_y_mm',
                    existing_type=sa.REAL(),
                    comment=None)

    # op.add_column('pfs_config_fiber',
    #               sa.Column('pfi_nominal_final_y_mm', sa.REAL(), autoincrement=False, nullable=True))
    # op.add_column('pfs_config_fiber',
    #               sa.Column('pfi_nominal_final_x_mm', sa.REAL(), autoincrement=False, nullable=True))
    # op.alter_column('pfs_config_fiber', 'pfi_center_final_y_mm',
    #                 existing_type=sa.REAL(),
    #                 comment=None,
    #                 existing_comment='Final measured y-position on the PFI',
    #                 existing_nullable=True)
    # op.alter_column('pfs_config_fiber', 'pfi_center_final_x_mm',
    #                 existing_type=sa.REAL(),
    #                 comment=None,
    #                 existing_comment='Final measured x-position on the PFI',
    #                 existing_nullable=True)
    # op.drop_column('pfs_config_fiber', 'pfi_nominal_y_mm')
    # op.drop_column('pfs_config_fiber', 'pfi_nominal_x_mm')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #                 existing_type=sa.REAL(),
    #                 comment=None,
    #                 existing_comment='',
    #                 existing_nullable=True)
    # op.create_table('test',
    #                 sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    #                 sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
    #                 )
    # ### end Alembic commands ###
