"""Add pfs_design.design0 and pfs_design.variant

Revision ID: 69f7c10323f8
Revises: efd77f25bdcd
Create Date: 2022-11-14 13:33:25.894766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f7c10323f8'
down_revision = 'efd77f25bdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment='',
    #            existing_nullable=True)
    # op.create_foreign_key(None, 'agc_exposure', 'pfs_visit', ['pfs_visit_id'], ['pfs_visit_id'])
    # op.alter_column('pfs_config', 'pfs_design_id',
    #            existing_type=sa.BIGINT(),
    #            nullable=False,
    #            autoincrement=False)
    # op.alter_column('pfs_config', 'visit0',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            existing_comment='The first visit of the set',
    #            autoincrement=False)
    op.add_column('pfs_design', sa.Column('variant', sa.Integer(), nullable=True, comment='Counter of which variant of `designId0` we are. Requires `designId0`'))
    op.add_column('pfs_design', sa.Column('design_id0', sa.BigInteger(), nullable=True, comment='pfsDesignId of the pfsDesign we are a variant of. Requires `variant`'))

    # setting value to default and not nullable.
    op.execute("UPDATE pfs_design SET design_id0 = 0")
    op.alter_column('pfs_design', 'design_id0', nullable=False)

    # setting value to default and not nullable.
    op.execute("UPDATE pfs_design SET variant = 0")
    op.alter_column('pfs_design', 'variant', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfs_design', 'design_id0')
    op.drop_column('pfs_design', 'variant')
    # op.alter_column('pfs_config', 'visit0',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            existing_comment='The first visit of the set',
    #            autoincrement=False)
    # op.alter_column('pfs_config', 'pfs_design_id',
    #            existing_type=sa.BIGINT(),
    #            nullable=True,
    #            autoincrement=False)
    # op.drop_constraint(None, 'agc_exposure', type_='foreignkey')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment=None,
    #            existing_comment='',
    #            existing_nullable=True)
    # op.create_table('test',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
    # )
    # ### end Alembic commands ###
