"""fix INSTRM-1687 + add constraints

Revision ID: 6f6938f65a2f
Revises: 486f6afc1e07
Create Date: 2023-06-30 18:23:44.587438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6938f65a2f'
down_revision = '486f6afc1e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cobra_match', 'cobra_move', ['pfs_visit_id', 'iteration', 'cobra_id'], ['pfs_visit_id', 'iteration', 'cobra_id'])
    op.create_unique_constraint(None, 'cobra_move', ['pfs_visit_id', 'iteration', 'cobra_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cobra_move', type_='unique')
    op.drop_constraint(None, 'cobra_match', type_='foreignkey')
    # ### end Alembic commands ###
