"""add proposal_id and ob_code

Revision ID: 77d27b6d1431
Revises: ec7b3ec7e815
Create Date: 2023-11-07 10:47:07.818852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d27b6d1431'
down_revision = 'ec7b3ec7e815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pfs_design_fiber', sa.Column('proposal_id', sa.String(), nullable=True, comment='Proposal ID'))
    op.add_column('pfs_design_fiber', sa.Column('ob_code', sa.String(), nullable=True, comment='OB code'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfs_design_fiber', 'ob_code')
    op.drop_column('pfs_design_fiber', 'proposal_id')
    # ### end Alembic commands ###
