"""update to 0.2.0

Revision ID: 910c4ead6bc1
Revises: 4b795e4f3a76
Create Date: 2022-04-27 10:25:40.726994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910c4ead6bc1'
down_revision = '4b795e4f3a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #           existing_type=sa.REAL(),
    #           comment='',
    #           existing_nullable=True)
    #op.create_foreign_key(None, 'agc_exposure', 'pfs_visit', ['pfs_visit_id'], ['pfs_visit_id'])
    op.add_column('fiducial_fiber', sa.Column('mask', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'fiducial_fiber_match', ['pfs_visit_id', 'iteration', 'fiducial_fiber_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiducial_fiber_match', type_='unique')
    op.drop_column('fiducial_fiber', 'mask')
    #op.drop_constraint(None, 'agc_exposure', type_='foreignkey')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #           existing_type=sa.REAL(),
    #           comment=None,
    #           existing_comment='',
    #           existing_nullable=True)
    # op.create_table('test',
    #sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
    #)
    # ### end Alembic commands ###
