"""iic_sequence.visit_set_id -> iic_sequence_id

Revision ID: 9a6d3c101e2c
Revises: b13b0e542938
Create Date: 2022-10-18 19:00:45.565704

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '9a6d3c101e2c'
down_revision = 'b13b0e542938'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iic_sequence', 'visit_set_id', new_column_name='iic_sequence_id')
    op.alter_column('iic_sequence_status', 'visit_set_id', new_column_name='iic_sequence_id')
    op.alter_column('visit_set', 'visit_set_id', new_column_name='iic_sequence_id')
    op.alter_column('field_set', 'visit_set_id', new_column_name='iic_sequence_id')
    op.alter_column('obslog_visit_set_note', 'visit_set_id', new_column_name='iic_sequence_id')

    op.alter_column('iic_sequence', 'iic_sequence_id',
                    existing_type=sa.INTEGER(),
                    comment='Sequence identifier',
                    existing_comment='Visit set identifier',
                    existing_nullable=False,
                    autoincrement=False)
    op.alter_column('iic_sequence_status', 'iic_sequence_id',
                    existing_type=sa.INTEGER(),
                    comment='Sequence identifier',
                    existing_comment='Visit set identifier',
                    existing_nullable=False,
                    autoincrement=False)

    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #                 existing_type=sa.REAL(),
    #                 comment='',
    #                 existing_nullable=True)
    # op.create_foreign_key(None, 'agc_exposure', 'pfs_visit', ['pfs_visit_id'], ['pfs_visit_id'])
    # 
    # op.alter_column('pfs_config', 'pfs_design_id',
    #                 existing_type=sa.BIGINT(),
    #                 nullable=False,
    #                 autoincrement=False)
    # op.alter_column('pfs_config', 'visit0',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=False,
    #                 existing_comment='The first visit of the set',
    #                 autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iic_sequence', 'iic_sequence_id', new_column_name='visit_set_id')
    op.alter_column('iic_sequence_status', 'iic_sequence_id', new_column_name='iic_sequence_id')
    op.alter_column('visit_set', 'iic_sequence_id', new_column_name='iic_sequence_id')
    op.alter_column('field_set', 'iic_sequence_id', new_column_name='iic_sequence_id')
    op.alter_column('obslog_visit_set_note', 'iic_sequence_id', new_column_name='iic_sequence_id')

    op.alter_column('iic_sequence', 'visit_set_id',
                    existing_type=sa.INTEGER(),

                    comment='Visit set identifier',
                    existing_comment='Sequence identifier',
                    existing_nullable=False,
                    autoincrement=False)
    op.alter_column('iic_sequence_status', 'iic_sequence_id',
                    existing_type=sa.INTEGER(),
                    comment='Visit set identifier',
                    existing_comment='Sequence identifier',
                    existing_nullable=False,
                    autoincrement=False)
    # ### end Alembic commands ###
