"""fix INFRA-335

Revision ID: 9b65fd3a8478
Revises: f17be2e93767
Create Date: 2024-08-22 10:00:52.212797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b65fd3a8478'
down_revision = 'f17be2e93767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcs_data', sa.Column('flux', sa.REAL(), nullable=True, comment='The measured flux'))
    op.add_column('mcs_data', sa.Column('fluxerr', sa.REAL(), nullable=True, comment='The measured flux error'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcs_data', 'fluxerr')
    op.drop_column('mcs_data', 'flux')
    # ### end Alembic commands ###
