"""add m2_off3 column to tel_status

Revision ID: aa5ab36a351a
Revises: 9b65fd3a8478
Create Date: 2025-01-26 01:55:09.706149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5ab36a351a'
down_revision = '9b65fd3a8478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tel_status', sa.Column('m2_off3', sa.REAL(), nullable=True, comment='Hexapod focus offset [mm]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tel_status', 'm2_off3')
    # ### end Alembic commands ###
