"""fix for INSTRM-2015

Revision ID: dfe39841eb0c
Revises: 6f6938f65a2f
Create Date: 2023-07-07 14:37:58.799597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe39841eb0c'
down_revision = '6f6938f65a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cobra_match_pfs_visit_id_fkey', 'cobra_match', type_='foreignkey')
    op.create_foreign_key(None, 'cobra_match', 'cobra_target', ['pfs_visit_id', 'iteration', 'cobra_id'], ['pfs_visit_id', 'iteration', 'cobra_id'])
    op.drop_constraint('cobra_move_pfs_visit_id_fkey', 'cobra_move', type_='foreignkey')
    # op.create_foreign_key(None, 'cobra_move', 'cobra_match', ['pfs_visit_id', 'iteration', 'cobra_id'], ['pfs_visit_id', 'iteration', 'cobra_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'cobra_move', type_='foreignkey')
    op.create_foreign_key('cobra_move_pfs_visit_id_fkey', 'cobra_move', 'cobra_target', ['pfs_visit_id', 'iteration', 'cobra_id'], ['pfs_visit_id', 'iteration', 'cobra_id'])
    op.drop_constraint(None, 'cobra_match', type_='foreignkey')
    op.create_foreign_key('cobra_match_pfs_visit_id_fkey', 'cobra_match', 'cobra_move', ['pfs_visit_id', 'iteration', 'cobra_id'], ['pfs_visit_id', 'iteration', 'cobra_id'])
    # ### end Alembic commands ###
