"""add match_mask in fiducial_fiber_match

Revision ID: e8c13289241d
Revises: 3c79be472316
Create Date: 2025-06-06 08:43:20.367505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c13289241d'
down_revision = '3c79be472316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiducial_fiber_match', sa.Column('match_mask', sa.Integer(), nullable=True, comment='mask for FF match (1 for FFs used in outer ring, 2 for FFs used in first iteration of transformation, 4 for FFs used in final transformation.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiducial_fiber_match', 'match_mask')
    # ### end Alembic commands ###
