"""update for INSTRM-2048

Revision ID: ec7b3ec7e815
Revises: ddeb04402bbc
Create Date: 2023-08-23 08:33:46.062843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7b3ec7e815'
down_revision = 'ddeb04402bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiducial_fiber_match', sa.Column('pfi_center_x_mm', sa.REAL(), nullable=True, comment='Actual x-position on the PFI [mm]'))
    op.add_column('fiducial_fiber_match', sa.Column('pfi_center_y_mm', sa.REAL(), nullable=True, comment='Actual y-position on the PFI [mm]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiducial_fiber_match', 'pfi_center_y_mm')
    op.drop_column('fiducial_fiber_match', 'pfi_center_x_mm')
    # ### end Alembic commands ###
