"""opdb summit schema updated to 0.2.8

Revision ID: ecf87508e91f
Revises: fe8612d2acdd
Create Date: 2023-04-17 17:39:57.971426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf87508e91f'
down_revision = 'fe8612d2acdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agc_data', sa.Column('estimated_magnitude', sa.REAL(), nullable=True, comment='The estimated magnitude of the object'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agc_data', 'estimated_magnitude')
    # ### end Alembic commands ###
