"""fix unique constraints

Revision ID: efa0e46d3dc9
Revises: 44bb95de7b0b
Create Date: 2021-06-30 09:48:05.025015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa0e46d3dc9'
down_revision = '44bb95de7b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test')
    op.alter_column('agc_data', 'image_moment_00_pix',
                    existing_type=sa.REAL(),
                    comment='',
                    existing_nullable=True)
    op.create_unique_constraint(None, 'agc_data', ['agc_exposure_id', 'agc_camera_id', 'spot_id'])
    op.create_unique_constraint(None, 'agc_exposure', ['agc_exposure_id'])
    op.create_unique_constraint(None, 'cobra_match', ['pfs_visit_id', 'iteration', 'cobra_id'])
    op.create_unique_constraint(None, 'cobra_target', ['pfs_visit_id', 'iteration', 'cobra_id'])
    op.create_unique_constraint(None, 'mcs_pfi_transformation', ['mcs_frame_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcs_pfi_transformation', type_='unique')
    op.drop_constraint(None, 'cobra_target', type_='unique')
    op.drop_constraint(None, 'cobra_match', type_='unique')
    op.drop_constraint(None, 'agc_exposure', type_='unique')
    op.drop_constraint(None, 'agc_data', type_='unique')
    op.alter_column('agc_data', 'image_moment_00_pix',
                    existing_type=sa.REAL(),
                    comment=None,
                    existing_comment='',
                    existing_nullable=True)
    op.create_table('test',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
                    )
    # ### end Alembic commands ###
