"""add iic_sequence.created_at and iic_sequence_status.finished_at

Revision ID: efd77f25bdcd
Revises: 102a149a18d6
Create Date: 2022-11-01 13:21:18.855718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd77f25bdcd'
down_revision = '102a149a18d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment='',
    #            existing_nullable=True)
    # op.create_foreign_key(None, 'agc_exposure', 'pfs_visit', ['pfs_visit_id'], ['pfs_visit_id'])
    op.add_column('iic_sequence', sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation time [YYYY-MM-DDThh:mm:ss]'))
    op.add_column('iic_sequence_status', sa.Column('finished_at', sa.DateTime(), nullable=True, comment='End time [YYYY-MM-DDThh:mm:ss]'))
    # op.alter_column('pfs_config', 'pfs_design_id',
    #            existing_type=sa.BIGINT(),
    #            nullable=False,
    #            autoincrement=False)
    # op.alter_column('pfs_config', 'visit0',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            existing_comment='The first visit of the set',
    #            autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('pfs_config', 'visit0',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            existing_comment='The first visit of the set',
    #            autoincrement=False)
    # op.alter_column('pfs_config', 'pfs_design_id',
    #            existing_type=sa.BIGINT(),
    #            nullable=True,
    #            autoincrement=False)
    op.drop_column('iic_sequence_status', 'finished_at')
    op.drop_column('iic_sequence', 'created_at')
    # op.drop_constraint(None, 'agc_exposure', type_='foreignkey')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment=None,
    #            existing_comment='',
    #            existing_nullable=True)
    # op.create_table('test',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)

    # ### end Alembic commands ###
