"""add fiber_status column in pfs_config_fiber table

Revision ID: f17be2e93767
Revises: de425faaa5dc
Create Date: 2023-12-01 12:30:41.638551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17be2e93767'
down_revision = 'de425faaa5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pfs_config_fiber', sa.Column('fiber_status', sa.Integer(), nullable=True, comment='fiberStatus: enumerated e.g. GOOD,BROKENFIBER,BLOCKED,BLACKSPOT'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfs_config_fiber', 'fiber_status')
    # ### end Alembic commands ###
