"""add pfs_config_fiber.target_ra,target_dec

Revision ID: fe8612d2acdd
Revises: 68dcfec061dc
Create Date: 2023-03-03 18:41:24.442932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8612d2acdd'
down_revision = '68dcfec061dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment='',
    #            existing_nullable=True)
    op.add_column('pfs_config_fiber', sa.Column('target_ra', sa.FLOAT(), nullable=True, comment='R.A. of the target'))
    op.add_column('pfs_config_fiber', sa.Column('target_dec', sa.FLOAT(), nullable=True, comment='Dec. of the target'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfs_config_fiber', 'target_dec')
    op.drop_column('pfs_config_fiber', 'target_ra')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment=None,
    #            existing_comment='',
    #            existing_nullable=True)
    # op.create_table('test',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
    # )
    # ### end Alembic commands ###
