"""add drp version

Revision ID: 1fccd2414131
Revises: d41162ba2cdf
Create Date: 2022-08-17 08:12:35.768262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fccd2414131'
down_revision = 'd41162ba2cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e2e_drp_version',
                    sa.Column('run_id', sa.Integer(), nullable=False),
                    sa.Column('drp2d_version', sa.String(), nullable=True, comment='DRP2D version'),
                    sa.Column('drp1d_amazed_version', sa.String(), nullable=True, comment='DRP1D (Amazed) version'),
                    sa.Column('drp1d_client_version', sa.String(), nullable=True, comment='DRP1D (PFS client) version'),
                    sa.ForeignKeyConstraint(['run_id'], ['e2e_processing.run_id'], ),
                    sa.PrimaryKeyConstraint('run_id')
                    )
    op.create_unique_constraint(None, 'e2e_sim_dataset', ['dataset_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'e2e_sim_dataset', type_='unique')
    op.drop_table('e2e_drp_version')
    # ### end Alembic commands ###
