"""add data_processing.rerun

Revision ID: 5a8968060139
Revises: 24b802710f00
Create Date: 2022-08-24 11:07:51.002224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8968060139'
down_revision = '24b802710f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_processing', sa.Column('rerun', sa.String(), nullable=True, comment='rerun name'))
    op.create_unique_constraint(None, 'data_processing', ['run_id'])
    op.create_unique_constraint(None, 'reduced_visits', ['pfs_visit_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reduced_visits', type_='unique')
    op.drop_constraint(None, 'data_processing', type_='unique')
    op.drop_column('data_processing', 'rerun')
    # ### end Alembic commands ###
