"""test

Revision ID: 7a1f3360020b
Revises: 
Create Date: 2022-08-09 11:02:20.421083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1f3360020b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'e2e_processing', ['run_id'])
    op.create_unique_constraint(None, 'test', ['test_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='unique')
    op.drop_constraint(None, 'e2e_processing', type_='unique')
    # ### end Alembic commands ###
