"""is_isred --> is_detrended

Revision ID: c19644cae10c
Revises: 5a8968060139
Create Date: 2022-08-24 11:14:46.541290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19644cae10c'
down_revision = '5a8968060139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reduced_visits', 'is_isred', nullable=True, new_column_name='is_detrended')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reduced_visits', 'is_detrended', nullable=True, new_column_name='is_isred')
    # ### end Alembic commands ###
