"""test

Revision ID: d41162ba2cdf
Revises: 7a1f3360020b
Create Date: 2022-08-09 15:17:17.584507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41162ba2cdf'
down_revision = '7a1f3360020b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e2e_sim_dataset',
    sa.Column('dataset_id', sa.Integer(), autoincrement=True, nullable=False, comment='sim dataset id'),
    sa.Column('dataset_description', sa.String(), nullable=True, comment='sim dataset description'),
    sa.Column('sim2d_version', sa.String(), nullable=True, comment='simulator version for the dataset'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='datetime that the dataset was made'),
    sa.PrimaryKeyConstraint('dataset_id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.add_column('e2e_processing', sa.Column('run_dataset', sa.Integer(), nullable=True, comment='sim dataset id'))
    op.create_foreign_key(None, 'e2e_processing', 'e2e_sim_dataset', ['run_dataset'], ['dataset_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'e2e_processing', type_='foreignkey')
    op.drop_column('e2e_processing', 'run_dataset')
    op.drop_table('e2e_sim_dataset')
    # ### end Alembic commands ###
