"""fix pkey in reduced_visits

Revision ID: d88cc9faea5c
Revises: 6b6cfe820b43
Create Date: 2022-08-24 17:02:44.687116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88cc9faea5c'
down_revision = '6b6cfe820b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
