"""test

Revision ID: 2399eba62c60
Revises: 
Create Date: 2020-07-24 23:39:05.417901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2399eba62c60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
