"""update to 0.1.10

Revision ID: 3078fbf3ffdb
Revises: 431d0bb8a39d
Create Date: 2021-11-18 20:18:33.084536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3078fbf3ffdb'
down_revision = '431d0bb8a39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obslog_fits_header',
                    sa.Column('pfs_visit_id', sa.Integer(), nullable=True),
                    sa.Column('filestem', sa.String(), nullable=False),
                    sa.Column('hdu_index', sa.Integer(), nullable=False),
                    sa.Column('cards_dict', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('cards_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.ForeignKeyConstraint(['pfs_visit_id'], ['pfs_visit.pfs_visit_id'], ),
                    sa.PrimaryKeyConstraint('filestem', 'hdu_index')
                    )
    op.create_index(op.f('ix_obslog_fits_header_pfs_visit_id'), 'obslog_fits_header', ['pfs_visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obslog_fits_header_pfs_visit_id'), table_name='obslog_fits_header')
    op.drop_table('obslog_fits_header')
    # ### end Alembic commands ###
