"""empty message

Revision ID: 60f6e707c30e
Revises: a4010ebbc09d
Create Date: 2022-09-01 17:26:30.532677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f6e707c30e'
down_revision = 'a4010ebbc09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agc_data', 'image_moment_00_pix',
               existing_type=sa.REAL(),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agc_data', 'image_moment_00_pix',
               existing_type=sa.REAL(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
