"""empty message

Revision ID: 6444ae35fa0e
Revises: b3091cf93c60
Create Date: 2022-09-01 15:51:15.356467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6444ae35fa0e'
down_revision = 'b3091cf93c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agc_data', 'image_moment_00_pix',
               existing_type=sa.REAL(),
               comment='',
               existing_nullable=True)
    op.drop_constraint('obslog_visit_set_note_visit_set_id_fkey', 'obslog_visit_set_note', type_='foreignkey')
    op.create_foreign_key(None, 'obslog_visit_set_note', 'iic_sequence', ['visit_set_id'], ['visit_set_id'])
    op.drop_constraint('processing_status_visit_set_id_fkey', 'processing_status', type_='foreignkey')
    op.drop_constraint('visit_set_visit_set_id_fkey', 'visit_set', type_='foreignkey')
    op.drop_constraint('visit_set_pfs_visit_id_fkey', 'visit_set', type_='foreignkey')
    op.create_foreign_key(None, 'visit_set', 'pfs_visit', ['pfs_visit_id'], ['pfs_visit_id'])
    op.create_foreign_key(None, 'visit_set', 'iic_sequence', ['visit_set_id'], ['visit_set_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_set', type_='foreignkey')
    op.drop_constraint(None, 'visit_set', type_='foreignkey')
    op.create_foreign_key('visit_set_pfs_visit_id_fkey', 'visit_set', 'sps_visit', ['pfs_visit_id'], ['pfs_visit_id'])
    op.create_foreign_key('visit_set_visit_set_id_fkey', 'visit_set', 'sps_sequence', ['visit_set_id'], ['visit_set_id'])
    op.create_foreign_key('processing_status_visit_set_id_fkey', 'processing_status', 'sps_sequence', ['visit_set_id'], ['visit_set_id'])
    op.drop_constraint(None, 'obslog_visit_set_note', type_='foreignkey')
    op.create_foreign_key('obslog_visit_set_note_visit_set_id_fkey', 'obslog_visit_set_note', 'sps_sequence', ['visit_set_id'], ['visit_set_id'])
    op.alter_column('agc_data', 'image_moment_00_pix',
               existing_type=sa.REAL(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
