"""update to 0.1.4

Revision ID: b3091cf93c60
Revises: c43ebb2b074d
Create Date: 2021-07-14 07:58:15.132306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3091cf93c60'
down_revision = 'c43ebb2b074d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iic_sequence',
                    sa.Column('visit_set_id', sa.Integer(), autoincrement=False, nullable=False, comment='Visit set identifier'),
                    sa.Column('sequence_type', sa.String(), nullable=True, comment='Sequence type'),
                    sa.Column('name', sa.String(), nullable=True, comment='The unique name assigned to this set of visits'),
                    sa.Column('comments', sa.String(), nullable=True, comment='Comments for the sequence'),
                    sa.Column('cmd_str', sa.String(), nullable=True, comment='ICS command string that generates exposures for this set of visits'),
                    sa.PrimaryKeyConstraint('visit_set_id')
                    )
    op.create_table('iic_sequence_status',
                    sa.Column('visit_set_id', sa.Integer(), autoincrement=False, nullable=False, comment='Visit set identifier'),
                    sa.Column('status_flag', sa.Integer(), nullable=True, comment='Status flag of the sequence'),
                    sa.Column('cmd_output', sa.String(), nullable=True, comment='Status output'),
                    sa.ForeignKeyConstraint(['visit_set_id'], ['iic_sequence.visit_set_id'], ),
                    sa.PrimaryKeyConstraint('visit_set_id')
                    )
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #                existing_type=sa.REAL(),
    #                comment='',
    #                existing_nullable=True)
    op.add_column('sps_camera', sa.Column('sps_camera_name', sa.String(length=2), nullable=True, comment='SpS camera name [e.g. "b3"]'))
    op.add_column('sps_camera', sa.Column('sps_module_name', sa.String(length=3), nullable=True, comment='SpS module name [e.g. "sm3"]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sps_camera', 'sps_module_name')
    op.drop_column('sps_camera', 'sps_camera_name')
    op.alter_column('agc_data', 'image_moment_00_pix',
                    existing_type=sa.REAL(),
                    comment=None,
                    existing_comment='',
                    existing_nullable=True)
    op.create_table('test',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
                    )
    op.drop_table('iic_sequence_status')
    op.drop_table('iic_sequence')
    # ### end Alembic commands ###
