"""fix a typo 20210701

Revision ID: c43ebb2b074d
Revises: d218ca946933
Create Date: 2021-07-02 10:51:59.611403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43ebb2b074d'
down_revision = 'd218ca946933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #           existing_type=sa.REAL(),
    #           comment='',
    #           existing_nullable=True)
    op.create_unique_constraint(None, 'camera_model_f3c_mcs', ['mcs_frame_id'])
    op.alter_column('cobra', 'sunns_id', new_column_name='sunss_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cobra', 'sunss_id', new_column_name='sunns_id')
    op.drop_constraint(None, 'camera_model_f3c_mcs', type_='unique')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #                existing_type=sa.REAL(),
    #                comment=None,
    #                existing_comment='',
    #                existing_nullable=True)
    # op.create_table('test',
    #                sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    #                sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
    #                )
    # ### end Alembic commands ###
