"""update to 0.1.1

Revision ID: d218ca946933
Revises: efa0e46d3dc9
Create Date: 2021-07-01 12:06:54.326469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd218ca946933'
down_revision = 'efa0e46d3dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiducial_fiber_calib',
                    sa.Column('fiducial_fiber_calib_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('calibrated_at', sa.DateTime(), nullable=True, comment='Date of the calibration [YYYY-MM-DDhh:mm:ss]'),
                    sa.Column('comments', sa.String(), nullable=True, comment='Comments'),
                    sa.PrimaryKeyConstraint('fiducial_fiber_calib_id')
                    )
    op.create_table('camera_model_f3c_mcs',
                    sa.Column('mcs_frame_id', sa.Integer(), autoincrement=False, nullable=False, comment='MCS frame identifier as generated from Gen2'),
                    sa.Column('matrix', sa.ARRAY(sa.REAL()), nullable=True, comment='camMatrix'),
                    sa.Column('distor', sa.ARRAY(sa.REAL()), nullable=True, comment='camDistor'),
                    sa.Column('rot_vector', sa.ARRAY(sa.REAL()), nullable=True, comment='camRotVec'),
                    sa.Column('tran_vector', sa.ARRAY(sa.REAL()), nullable=True, comment='camTranVec'),
                    sa.ForeignKeyConstraint(['mcs_frame_id'], ['mcs_exposure.mcs_frame_id'], ),
                    sa.PrimaryKeyConstraint('mcs_frame_id'),
                    sa.UniqueConstraint('mcs_frame_id')
                    )
    # op.drop_table('test')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #                existing_type=sa.REAL(),
    #                comment='',
    #                existing_nullable=True)
    op.add_column('cobra', sa.Column('cobra_board_id', sa.Integer(), nullable=True, comment='Cobra board id (1..84). One Cobra module has two boards.'))
    op.add_column('cobra', sa.Column('cobra_in_board', sa.Integer(), nullable=True, comment='Cobra-in-board (1..29). Each board has either 29 or 28 cobras.'))
    op.add_column('cobra', sa.Column('cobra_module_id', sa.Integer(), nullable=True, comment='Cobra module id (1..42)'))
    op.add_column('cobra', sa.Column('fiber_id', sa.Integer(), nullable=True, comment='The fiber identifier (1..2604). This is a unique identifier for each fiber (both science and engineering). fiberId = 651*(sp-1)+fh.'))
    op.add_column('cobra', sa.Column('mtp', sa.String(length=3), nullable=True, comment='Cobra module id associated with MTP ferrule. There are 84 of these, numbered 1 through 42 with A and B suffixes. (e.g.,13B)'))
    op.add_column('cobra', sa.Column('mtp_a_id', sa.String(), nullable=True, comment='Identifier of the USCONNEC connector hole at the Cable B-C interface. MTP = A)'))
    op.add_column('cobra', sa.Column('mtp_ba_id', sa.String(), nullable=True, comment='Identifier of the USCONNEC connector hole at the Cable B-C interface. MTP = BA)'))
    op.add_column('cobra', sa.Column('mtp_bc_id', sa.String(), nullable=True, comment='Identifier of the USCONNEC connector hole at the Cable B-C interface. MTP = BC)'))
    op.add_column('cobra', sa.Column('mtp_c_id', sa.String(), nullable=True, comment='Identifier of the USCONNEC connector hole at the Cable B-C interface. MTP = C)'))
    op.add_column('cobra', sa.Column('science_fiber_id', sa.Integer(), nullable=True, comment=' Science fiber (1..2394). This is a unique identifier for each science fiber.'))
    op.add_column('cobra', sa.Column('sps_module_id', sa.Integer(), nullable=True, comment='Spectrograph that the cobra feeds (1..4)'))
    op.add_column('cobra', sa.Column('sps_slit_hole', sa.Integer(), nullable=True, comment='Fiber hole (1..651). This is the position in the spectrograph slit head.'))
    op.add_column('cobra', sa.Column('sunns_id', sa.String(length=4), nullable=True, comment='SuNSS fiber id. ID consists of fiber number and mode (i is imaging, and d is diffuse).'))
    op.add_column('cobra', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('cobra', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('cobra', 'cobra_id',
                    existing_type=sa.INTEGER(),
                    comment='Cobra identifier (1..2394). There is one of these for each science fiber.',
                    autoincrement=False)
    op.alter_column('cobra', 'cobra_in_field',
                    existing_type=sa.INTEGER(),
                    comment='Cobra-in-field (1..798). cf = 57*(mf-1)+cm.',
                    existing_nullable=True)
    op.alter_column('cobra', 'cobra_in_module',
                    existing_type=sa.INTEGER(),
                    comment='Cobra-in-module (1..57). 1 is the bottom-left cobra in a module when looked at with the wide (29-cobra) board down. Increasing as you move across the module.',
                    existing_nullable=True)
    op.alter_column('cobra', 'field_on_pfi',
                    existing_type=sa.INTEGER(),
                    comment='Field (1..3).',
                    existing_nullable=True)
    op.alter_column('cobra', 'module_in_field',
                    existing_type=sa.INTEGER(),
                    comment='Module-in-field (1..14). The number of the module within the field, with 1 at the center of the PFI.',
                    existing_nullable=True)
    op.drop_constraint('cobra_sps_camera_id_fkey', 'cobra', type_='foreignkey')
    op.drop_column('cobra', 'slit_hole_sps')
    op.drop_column('cobra', 'cobra_id_lna')
    op.drop_column('cobra', 'module_name')
    op.drop_column('cobra', 'cobra_id_sps')
    op.drop_column('cobra', 'sps_camera_id')
    op.add_column('fiducial_fiber_geometry', sa.Column('ambient_temp', sa.REAL(), nullable=True, comment='Ambient temperature'))
    op.add_column('fiducial_fiber_geometry', sa.Column('elevation', sa.REAL(), nullable=True, comment='Elevation'))
    op.add_column('fiducial_fiber_geometry', sa.Column('fiducial_fiber_calib_id', sa.Integer(), autoincrement=False, nullable=False))
    op.create_unique_constraint(None, 'fiducial_fiber_geometry', ['fiducial_fiber_id', 'fiducial_fiber_calib_id'])
    op.create_foreign_key(None, 'fiducial_fiber_geometry', 'fiducial_fiber_calib', ['fiducial_fiber_calib_id'], ['fiducial_fiber_calib_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiducial_fiber_geometry', type_='foreignkey')
    op.drop_constraint(None, 'fiducial_fiber_geometry', type_='unique')
    op.drop_column('fiducial_fiber_geometry', 'fiducial_fiber_calib_id')
    op.drop_column('fiducial_fiber_geometry', 'elevation')
    op.drop_column('fiducial_fiber_geometry', 'ambient_temp')
    op.add_column('cobra', sa.Column('sps_camera_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cobra', sa.Column('cobra_id_sps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cobra', sa.Column('module_name', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('cobra', sa.Column('cobra_id_lna', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('cobra', sa.Column('slit_hole_sps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cobra_sps_camera_id_fkey', 'cobra', 'sps_camera', ['sps_camera_id'], ['sps_camera_id'])
    op.alter_column('cobra', 'module_in_field',
                    existing_type=sa.INTEGER(),
                    comment=None,
                    existing_comment='Module-in-field (1..14). The number of the module within the field, with 1 at the center of the PFI.',
                    existing_nullable=True)
    op.alter_column('cobra', 'field_on_pfi',
                    existing_type=sa.INTEGER(),
                    comment=None,
                    existing_comment='Field (1..3).',
                    existing_nullable=True)
    op.alter_column('cobra', 'cobra_in_module',
                    existing_type=sa.INTEGER(),
                    comment=None,
                    existing_comment='Cobra-in-module (1..57). 1 is the bottom-left cobra in a module when looked at with the wide (29-cobra) board down. Increasing as you move across the module.',
                    existing_nullable=True)
    op.alter_column('cobra', 'cobra_in_field',
                    existing_type=sa.INTEGER(),
                    comment=None,
                    existing_comment='Cobra-in-field (1..798). cf = 57*(mf-1)+cm.',
                    existing_nullable=True)
    op.alter_column('cobra', 'cobra_id',
                    existing_type=sa.INTEGER(),
                    comment=None,
                    existing_comment='Cobra identifier (1..2394). There is one of these for each science fiber.',
                    autoincrement=False)
    op.drop_column('cobra', 'updated_at')
    op.drop_column('cobra', 'sunns_id')
    op.drop_column('cobra', 'sps_slit_hole')
    op.drop_column('cobra', 'sps_module_id')
    op.drop_column('cobra', 'science_fiber_id')
    op.drop_column('cobra', 'mtp_c_id')
    op.drop_column('cobra', 'mtp_bc_id')
    op.drop_column('cobra', 'mtp_ba_id')
    op.drop_column('cobra', 'mtp_a_id')
    op.drop_column('cobra', 'mtp')
    op.drop_column('cobra', 'fiber_id')
    op.drop_column('cobra', 'created_at')
    op.drop_column('cobra', 'cobra_module_id')
    op.drop_column('cobra', 'cobra_in_board')
    op.drop_column('cobra', 'cobra_board_id')
    op.alter_column('agc_data', 'image_moment_00_pix',
                    existing_type=sa.REAL(),
                    comment=None,
                    existing_comment='',
                    existing_nullable=True)
    op.create_table('test',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True)
                    )
    op.drop_table('camera_model_f3c_mcs')
    op.drop_table('fiducial_fiber_calib')
    # ### end Alembic commands ###
