"""add iic_sequence.created_at and iic_sequence_status.finished_at

Revision ID: dc5b82266e56
Revises: 7c023d532f3c
Create Date: 2022-11-01 12:42:18.113138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5b82266e56'
down_revision = '7c023d532f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment='',
    #            existing_nullable=True)
    op.add_column('iic_sequence', sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation time [YYYY-MM-DDThh:mm:ss]'))
    op.add_column('iic_sequence_status', sa.Column('finished_at', sa.DateTime(), nullable=True, comment='End time [YYYY-MM-DDThh:mm:ss]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iic_sequence_status', 'finished_at')
    op.drop_column('iic_sequence', 'created_at')
    # op.alter_column('agc_data', 'image_moment_00_pix',
    #            existing_type=sa.REAL(),
    #            comment=None,
    #            existing_comment='',
    #            existing_nullable=True)
    # ### end Alembic commands ###
